#!/usr/bin/env lua

string.count = function(str, s2)
  local count = 0
  for i = 1, #str do
    if str:sub(i,i) == s2 then
      count = count + 1
    end
  end
  return count
end

string.trim = function(s)
  return (s:gsub("^%s*(.-)%s*$", "%1"))
end

local indent_str = '  '

local level = 0

local braces = {
  {'{','}'},
  {'(',')'},
}

local posts = {
  ['^function%s*%(.*%)%s*$'] = 1, -- function ()
  ['.*%(.*function%s*%(.*%).*end'] = -1, -- ... (function () end
  ['.*%(.*function%s*%(.*%).*end%),'] = 1, -- ...(function () end)
  ['%([%w_,%s]*function%s*%(.*%)%s*$'] = 1, -- ...guard(function () end)
  ['^local%s+function%s*%([%w_,%s%.]*%)'] = 1,
  ['^local%s+function%s+[%w_]*%s*%([%w_,%s%.]*%)%s*$'] = 1,
  ['^local%s+[%w_]+%s*=%s*function%s*%([%w_,%s%.]*%)%s*$'] = 1,
  ['^[%w_%.]+%s*=%s*function%s*%([%w_,%s%.]*%)%s*$'] = 1,
  ['^[%w_%.]+%s*=%s*function%s*%([%w_,%s%.]*%)%s*end$'] = 1,
  ['^return%s+function%s*%([%w_,%s%.]*%)%s*$'] = 1,
  ['function%(%s*$'] = 1,
  ['.*then$'] = 1,
  ['^repeat%s*$'] = 1,
  ['.*do%s*$'] = 1,
  ['^else%s*$'] = 1,
  ['^end.*%)'] = -1,
}

local pres = {
  ['^end,?$'] = -1,
  ['^until.*'] = -1,
  ['else$'] = -1,
  ['elseif.*'] = -1,
}

local isolate = function(l)
  local pure = l:gsub('"[^"]*"','""')
  pure = pure:gsub("'[^']*'","''")
  return pure:match('(.*)%-%-.*') or pure
end

local debugp = function() end
if os.getenv('LUDENTDEBUG') == '1' then
  debugp = print
end

local indent = function(src,dst)
  assert(src,dst)
  for line in src:lines() do
    line = line:trim() or ''
    local pure = isolate(line)
    
    local pre = 0
    local post = 0
    
    debugp('------',pure)
    
    for _,b in pairs(braces) do
      local dif = pure:count(b[1]) - pure:count(b[2])
      debugp('-- BRACE',dif,level)
      if dif > 0 then
        post = post + dif
      elseif dif < 0 then
        pre = pre + dif
      end
    end
    
    for exp,inc in pairs(pres) do
      if pure:match(exp) then
        debugp('-- PRE',inc,level,exp,pure)
        pre = pre + inc
      end
    end
    
    for exp,inc in pairs(posts) do
      if pure:match(exp) then
        debugp('-- POST',inc,level,exp,pure)
        post = post + inc
      end
    end
    
    debugp('------')
    
    -- print('L',level,post,pre,dif)
    
    level = level + pre
    assert(level >=0,line..' (pre/'..level..')')
    
    dst:write(string.rep(indent_str,level)..line..'\n')
    
    level = level + post
    assert(level >=0,line..' (post/'..level..')')
  end
  assert(level==0,level)
end

if #arg == 0 then
  indent(io.stdin,io.stdout)
else
  local copy = function(src,dst)
    local data = src:read('*a')
    dst:write(data)
    dst:flush()
  end
  for _,f in ipairs(arg) do
    print('LUDENTING',f)
    local src = io.open(f)
    local tmp = io.tmpfile()
    indent(src,tmp)
    src:close()
    src = io.open(f,'w')
    tmp:flush()
    tmp:seek('set')
    copy(tmp,src)
  end
end
